Description:  Creating a SecurityGroup and an EC2 instance
# Exercise - Rollback
AWSTemplateFormatVersion: '2010-09-09'
Description: ND9991 C3 L4
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      ImageId: 'ami-052efd3df9dad4825'
      InstanceType: t2.micro
      KeyName: ansible

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 'Allow SSH and HTTP access'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: '0.0.0.0/0'
