# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

# Define a job to be invoked later in a workflow.
jobs:
  configure_ansible_infrastructure:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    docker:
      - image: python:3.7-alpine3.16
    # Add job steps
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:  ["43:d4:bd:9e:78:f4:ee:30:90:f5:79:a6:c0:e3:7b:ed"]
      - run:
          name: Install dependencies (ansible)
          command: |
            apk add --update ansible # Install ansible
      - run:
          name: Run your playbook to configure server
          command: |
            ansible-playbook -i inventory.txt main-remote.yml

  create_infrastructure:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    docker:
      - image: amazon/aws-cli
    # Add steps to the job. Steps to create a cloudformation stack
    steps:
      - checkout
      - run:
          name: "Create Cloudformation Stack"
          command: |
            aws cloudformation deploy \
            --template-file cf-template.yml \
            --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
            --region us-east-1

# Invoke jobs via workflows
workflows:
  ansible-setup-workflow:
    jobs:
      # - create_infrastructure
      - configure_ansible_infrastructure
