# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

# Define a job to be invoked later in a workflow.
jobs:
  configure_ansible_infrastructure:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    docker:
      - image: python:3.10.5-alpine3.16
    # Add job steps
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:  ["03:5f:a1:9c:a5:92:dd:00:cf:dc:36:ca:2d:d9:be:82"]

      - run:
          name: Install dependencies (openssh)
          command: |
            apk add --update openssh # Install openssh
      - run:
          name: Install git
          command: |
            apk add --update git # Install git

      - run:
          name: Install dependencies (ansible)
          command: |
            apk add --update ansible # Install ansible

      - run:
          name: Run your playbook to configure server
          command: |
            ansible-playbook main-remote.yml -i inventory.txt

  create_infrastructure:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    docker:
      - image: amazon/aws-cli
    # Add steps to the job. Steps to create a cloudformation stack
    steps:
      - checkout
      - run:
          name: "Create Cloudformation Stack"
          command: |
            aws cloudformation deploy \
            --template-file cf-template.yml \
            --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
            --region us-east-1
          # - when: on_fail # a command used to ignore errors
# Invoke jobs via workflows
workflows:
  ansible-setup-workflow:
    jobs:
      # - create_infrastructure
      - configure_ansible_infrastructure
