- name: "update apt packages."
  become: true
  apt:
    update_cache: yes

# - name: "upgrade packages"
#   become: true
#   apt:
#     upgrade: yes

- name: "Remove some dependences that are not required"
  become: true
  apt:
    autoremove: yes

- name: "Install Node.js and NPM"
  apt:
    name:
      - "nodejs"
      - "npm"
    state: latest
    update_cache: yes

- name: "Install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: latest

- name: "creates directory"
  file:
    path: ~/web
    state: directory

- name: "copy index text page"
  template:
    src: files/index.js
    dest: ~/web/index.js

- name: "executing node"
  shell:  pm2 start ~/web/index.js -f

